secrets:
  config:
    file: ./secrets.cfg
services:
  api:
    build: ./API
    volumes:
      - ./API:/api
    ports:
      - "3000:3000"
    secrets:
      - config
  mongo:
    image: "mongo:4.2.12-bionic"
    ports:
      - "27017:27017"